### ISSUE TITLE
Should BasicTokenizer add [CLS] token?

### ISSUE THREAD

**Issue by lapolonio** [tensorflow/text#146]
The basic test here: https://github.com/tensorflow/text/blob/master/tensorflow_text/python/ops/bert_tokenizer_test.py#L180 shows that the `[CLS]` token isn't added.

While the official Bert repo shows the token added: https://github.com/tensorflow/models/blob/master/official/nlp/bert/classifier_data_lib.py#L335

Is this a purposeful difference? If so why?

**Comment by thuang513** [comment]
The [CLS] token is a special token that signifies the beginning of a segment. 

We have kept the addition of special tokens (e.g. [CLS], [SEP], [MASKED], etc.) separate from the tokenizer itself so that you are able to manipulate the tokens and determine how to construct your segments separately. 

For example, you may tokenize a sentence and construct two segments (because sentence is > max_seq_len).

You can add special tokens using tf.concat.
