### ISSUE TITLE
Raspberry Pi Support

### ISSUE THREAD

**Issue by michaelnhw** [tensorflow/text#227]
Build from source is currently broken on Raspberry pi. When I tried to build using bazel, the following error occurs:

/root/.cache/bazel/_bazel_root/7ca663d4ab74a0b23905915c5a09aeae/external/com_goo
gle_absl/absl/strings/BUILD.bazel:83:1: C++ compilation of rule '@com_google_absl//absl
/strings:internal' failed (Exit 1)
Traceback (most recent call last):
  File "external/org_tensorflow/third_party/toolchains/preconfig/ubuntu16.04/gcc7_manyl
inux2010-nvcc-cuda10.0/clang/bin/crosstool_wrapper_driver_is_not_gcc", line 272, in <mo
dule>
    sys.exit(main())
  File "external/org_tensorflow/third_party/toolchains/preconfig/ubuntu16.04/gcc7_manylinux2010-nvcc-cuda10.0/clang/bin/crosstool_wrapper_driver_is_not_gcc", line 269, in main
    return subprocess.call([CPU_COMPILER] + cpu_compiler_flags)
  File "/usr/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/dt7/usr/bin/gcc': '/dt7/usr/bin/gcc'
Target //oss_scripts/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.979s, Critical Path: 0.47s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

The compilation process seems to rely on some cuda gcc. The procedure I used for building is as following:

1. bash oss_scripts/configure.sh
2. remove these 2 lines from WORKSPACE as they are causing patch error: patches = ["//third_party/icu:udata.patch"], patch_args = ["-p1"]
3. bazel build oss_scripts/pip_package:build_pip_package

**Comment by broken** [comment]
The references to '/dt7/usr/bin/gcc' come from TF's toolchain, which makes building inside their docker image necessary if you build with it. I'm actually surprised this is coming up for you, because it should require building with the --config=manylinux2010 flag. In any case, you should be able to remove the reference to this in your .bazelrc file (or the configure.sh before running it).

With regards to the patch errors, my guess is that you previously built TF from source, so bazel has ICU cached, and they apply a similar (but different) patch to ICU as well. After building TF, I believe running `bazel clean` will remove the cached libraries and allow for the patching. IIRC, normalize_utf8, and BertTokenizer which uses it, are the only ops that depend on the patched ICU.
