### ISSUE TITLE
Tensorflow 1.x support?

### ISSUE THREAD

**Issue by matthen** [tensorflow/text#25]
Firstly, thanks for this code! It makes serializing and sharing text-based models much easier. We currently use custom ops for e.g. subword tokenization and would love to switch over to the one in this repo, facilitating sharing models over tf hub etc.

Is there any plan to support tensorflow 1.x versions?

**Comment by broken** [comment]
Initially we did not plan on it. There are some features coming out in the near future that we plan on taking advantage of in TF 2.0, and it seemed inappropriate to start with a 1.0 release and very soon move to a 2.0, and take on the burden of supporting two versions. I can't recall if there was anything missing in 1.x, but I see they now recently released 1.14 which should have everything. 

We also believed most uses would be coming from new projects which were starting in TF 2.0, since current projects probably already had something established they were using. However, if there is enough desire for 1.x support, perhaps we could do a single release for 1.14.x to address these users, with the knowledge that moving forward we only plan on supporting 2.x.

**Comment by matthen** [comment]
I'd like 1.x support at least for the custom op kernels, to help sharing serialized text encoding models to a broader audience

**Comment by broken** [comment]
Got it. We will be doing a 1.x release soon.

**Comment by broken** [comment]
We released a 1.x candidate (0.1.0rc2) that is fully compatible with TF 1.14.
