### ISSUE TITLE
How to install TensorFlow-text with TensorFlow-gpu?

### ISSUE THREAD

**Issue by HangCui0510** [tensorflow/text#435]
On compute canada, I am only allowed to pip install tensorflow-gpu, but tensorflow-text requries tensorflow installed instead of tensorflow-gpu. How do I install tensorflow-text with tensorflow-gpu?

**Comment by broken** [comment]
Moving forward (>= 2.4), tensorflow-gpu should be the default - there will be tensorflow and tensorflow-cpu. TF Text should work on either, but the problem is at install time. You just need to install the version you want to use after TF Text if it was removed.

Please see #195 for more information regarding where the complication with this lies.
