### ISSUE TITLE
Expose BasicTokenizer at the top level

### ISSUE THREAD

**Issue by fredo838** [tensorflow/text#542]
Currenlty the `BasicTokenizer` is exposed to users like this: 

`from tensorflow_text.python.ops.bert_tokenizer import BasicTokenizer`

I had to search for a long time before I found it. Could we expose it at the top level, like so:

`from tensorflow_text import BasicTokenizer`

which seems more in line with the other `Tokenizers`?

**Comment by broken** [comment]
The BasicTokenizer is what was used to tokenize before Wordpiece in the original BERT model. We built it to comply with the models from that paper, but do not necessarily believe it as a good representation of a "basic tokenizer", so we do not include it in the API docs or expose it at the top level.

We've discussed providing something more inline with what we believe a BasicTokenizer should be, but the desire seems small so it keeps getting pushed back due to other priorities.

**Comment by fredo838** [comment]
Allright
