### ISSUE TITLE
Resource localhost/_0_SentencepieceOp/N10tensorflow4text12_GLOBAL__N_121SentencepieceResourceE does not exist.

### ISSUE THREAD

**Issue by ChWick** [tensorflow/text#570]
Hi,

tensorflow_text crashes with a 
```
tensorflow.python.framework.errors_impl.NotFoundError:  Resource localhost/_0_SentencepieceOp/N10tensorflow4text12_GLOBAL__N_121SentencepieceResourceE does not exist.
	 [[node tok_model/SentenceTokenizer/SentenceTokenizer/SentenceTokenizer/SentenceTokenizer/SentenceTokenizer/SentencepieceTokenizeOp (defined at <string>:210) ]] [Op:__inference_train_function_582]
```
when calling `tf.random.set_seed` after creating the first model (first call to `SentencepiceTokenizer`)

See the attached colab to reproduce this error: https://colab.research.google.com/drive/1EmBn9RPbohbhfoP0LvqoUXvhgNR7h6XM?usp=sharing

I am not sure if this is a bug of tensorflow_text or tensorflow itself.

**Comment by broken** [comment]
I found this documentation:

> The behavior of the random ops is further complicated by the facts that kernels are cached by the eager runtime, random ops are stateful ops, and `tf.random.set_seed` function resets the kernel cache.

I suspect that the SentencePIece resource created by the TokModel is being cleared when the kernel cache is reset, so when you try to tokenize with it after, the SP resource no longer exists resulting in the error you are experiencing being thrown.

I don't know if TF will consider this a bug, but it might not be a bad idea for them to clear up in the documentation the consequences of the call. Note that the documentation I found above was never pushed to the API docs because it was labeled as having too many buzzwords and meaningless details for the average user.

**Comment by ChWick** [comment]
Thanks for the quick response. I observe the same in graph and eager mode, but due to same reason, I guess. I close this, since this issue can easily be circumvented by taking care of the order of `tf.random.set_seed` and creating the model.
