### ISSUE TITLE
Creating custom normalizer

### ISSUE THREAD

**Issue by mmousavi5** [tensorflow/text#621]
At first thanks a lot for this awesome repo.
I tried to find normalizer code in this package to develop custom normalizer for some RTL languages like Arabic but as you mentioned in comments:

> normalization is implicitly applied to the strings

Is there any way to create custom normalizer?
Would you please give me some  guidance to implement custom normalizer?

**Comment by edloper** [comment]
It looks like the string you are quoting is from the docs for [`tf.text.case_fold_utf8`](https://github.com/tensorflow/text/blob/master/docs/api_docs/python/text/case_fold_utf8.md).  Are you doing case-folding, or are you trying to do some other form of normalization?  

If you are performing a standard unicode normalization (one of the normalizations described in http://unicode.org/reports/tr15/), then you could use [`tf.text.normalize_utf8`](https://github.com/tensorflow/text/blob/master/docs/api_docs/python/text/normalize_utf8.md).

Some types of normalization could be accomplished using `tf.strings.regex_replace`.  E.g., if you wanted to normalize one character to another, you could use `tf.strings.regex_replace(my_data, old_char, new_char)`.  However, if you have a lot of different normalization rules you need to apply, then this might not be very efficient (since it will need to make one pass over the inputs for each rule).  

If none of these solutions work, then you might need to write a custom TensorFlow op in c++.  See [this page](https://www.tensorflow.org/guide/create_op) for details.

**Comment by mmousavi5** [comment]
@edloper thanks for your response, i'm going to write custom op in c++ because there are lots of rules and characters replacement and it would be better to implement them efficiently.But there is another question, is it possible to find source code of `_normalize_ops.so` because I'm really interested to see how this op is implemented.

**Comment by broken** [comment]
@mmousavi5 The code for it is in the core/kernels subdirectory.

https://github.com/tensorflow/text/blob/master/tensorflow_text/core/kernels/normalize_kernels.cc
