### ISSUE TITLE
Error with string output wordpiece tokenization

### ISSUE THREAD

**Issue by matthen** [tensorflow/text#72]
I am finding an error when trying to do wordpiece tokenization, with string subtoken output:

```python
import tensorflow as tf
import tensorflow_text as tf_text

sess = tf.InteractiveSession()
y = tf.constant(["ab", "a", "c"], dtype=tf.string)
vocab = tf.lookup.KeyValueTensorInitializer(
    keys=y, values=y,
    key_dtype=tf.string,
    value_dtype=tf.string,
)
vocab_lookup_table = tf.lookup.StaticHashTable(vocab, "")
tokenizer = tf_text.WordpieceTokenizer(
    vocab_lookup_table=vocab_lookup_table,
    token_out_type=tf.string,
    unknown_token=None,
    suffix_indicator="",
)
sess.run(tf.tables_initializer())
print(
    sess.run(tokenizer.tokenize(["abc", "ad"]))
)
```

I would expect the output `[["ab", "c"], ["a", "d"]]`, but actually see:

```
F tensorflow/core/framework/tensor.cc:624] Check failed: dtype() == expected_dtype (9 vs. 7) string expected, got int64
Abort trap: 6
```

tensorflow_text version 0.1.0rc2, tensorflow version 1.14.0

**Comment by matthen** [comment]
I fixed this with 

```
vocab = tf.lookup.KeyValueTensorInitializer(
    keys=y, values=tf.range(3, dtype=tf.int64),
    key_dtype=tf.string,
    value_dtype=tf.int64,
)
vocab_lookup_table = tf.lookup.StaticHashTable(vocab, -1)
```

so the values have to be `int64`, though they aren't ever surfaced.

**Comment by broken** [comment]
Apologies for the late reply, but your right about the changes you needed. First of all, I thought we had an example of Wordpiece, but it looks like it only made it to the [release blog post](https://medium.com/tensorflow/introducing-tf-text-438c8552bd5e) ([gist example](https://gist.github.com/broken/cfc83b21912a4c5c605073d8a6e4f024#file-wordpiecetokenizer-example-py)). I'll work on getting this in more of the tutorials.

Anyway, there are a few things I should point out. First, if a subword is not in the vocabulary, the whole word will be marked as unknown. So, with a vocab of ["ab", "a", "c"], the string "ad" will be marked unknown instead of ["a", "d"].

Second, subwords are marked with a character prefix (the default is '##'). So, with a vocab of ["ab", "a", "c"] and the default prefix '##', the string "abc" will also be marked as unknown. You instead will need a vocab of ["ab", "a", "##c"] to have it return as ["ab", "##c"].

And finally, the lookup table should map strings to integers. When building the models, you need to convert text into numbers, and looking up in this table is actually what performs that lookup and is surfaced when choosing the token_out_type (which defaults to int64). Example:

vocab = ["ab", "b", "##"c] maps to [0, 1, 2] with out of vocab values mapping to 4.

wp.tokenize(vocab, ["abc", "ad"], token_out_type=tf.string) = [["ab", "##c"], ["[UNK]"]]

wp.tokenize(vocab, ["abc", "ad"], token_out_type=tf.int64) = [[0, 2], [4]]
