### ISSUE TITLE
import fails

### ISSUE THREAD

**Issue by rzaayshan** [tensorflow/text#961]
I get this error when I import tensorflow_text on colab

NotFoundError                             Traceback (most recent call last)
[<ipython-input-12-566f9fbfe6f7>](https://localhost:8080/#) in <module>()
      1 import tensorflow_hub as hub
----> 2 import tensorflow_text as text

3 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/load_library.py](https://localhost:8080/#) in load_op_library(library_filename)
     52     A python module containing the Python wrappers for Ops defined in
     53     the plugin.
---> 54 
     55   Raises:
     56     RuntimeError: when unable to load the library or get the python wrappers.

NotFoundError: /usr/local/lib/python3.7/dist-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb

**Comment by broken** [comment]
That error normally occurs when you are running a version of tensorflow_text that was not built for a particular version of TF. Example: TF Text 2.8.0 and TF 2.9.0. Is this still occurring for you? Colab was also having issues a couple weeks ago (see #963) which have since been fixed that may have also been the cause.

ps. Apologies; this issue somehow got lost triage.
